### ISSUE TITLE
make-docs-accessible

### ISSUE THREAD

**Issue by coden-s** [kuhlkena/VirtualRocks#114]
currently, we can only get to the docs from within the app.

if we have instructions for installing the project in the docs, we should have the docs accessible from outside of the app, preferably from the github page but could be elsewhere.

**Comment by kuhlkena** [comment]
oops

**Comment by coden-s** [comment]
could be done through readthedocs, or we can try to do it through github

**Comment by coden-s** [comment]
depends on #146 
and me actually doing it lmao
