### ISSUE TITLE
info-menu

### ISSUE THREAD

**Issue by kuhlkena** [kuhlkena/VirtualRocks#12]

**Comment by coden-s** [comment]
ok, assuming that the 'new' and 'open' things in the menu will allow the user to make a new project or open an existing one, we should probs also make it so there's some check to see if the project that's currently opened is saved.
I guess everything already just kinda autosaves (cuz everything just makes a file), but do we need to do anything to kill colmap/pymeshlab if we're no longer using the actively open project?

**Comment by coden-s** [comment]
starting to think it will be best to just do new/open by reopening start menu. makes code simpler and also makes menu look a lot nicer probs.

**Comment by coden-s** [comment]
if we reopen the start menu, do we want to delete the page2 that's already there and start fresh? There's issues with swapping styles and maintaining the map that I don't really understand. Probably because I'm not sure of how the basics of the code work 'cuz they were there before I started.

**Comment by coden-s** [comment]
map disappears when going back to start menu on goblin mode (with dark map), going to light mode, then going to dark mode. Map isn't recoverable unless you go back to start menu. need to better understand how the map is being displayed.

**Comment by coden-s** [comment]
thing to do, putting here so I don't forget: move the light/dark/goblin stuff out of main and into appwindow
