### ISSUE TITLE
save-as

### ISSUE THREAD

**Issue by coden-s** [kuhlkena/VirtualRocks#170]
currently save and save as in the menu bar do nothing.

save really doesn't need to be there cuz we autosave and there's nothing to save between points (not rlly sure how the bounds stuff would save but it's also very easy to redo)

save as might be a good thing tho cuz we could let the user save their progress but under a new name. like change directory but change directory + name but keep all the progress.

either that or we remove both from the file menu.

**Comment by kuhlkena** [comment]
I vote to remove both. I don't think its really a core feature and it seems a bit like a niche issue. Especially because unless you were copying the entire project dir then you would end up with multiple pkl files that refer to the same stuff which always causes issues
