### ISSUE TITLE
fullscreen-toggle

### ISSUE THREAD

**Issue by coden-s** [kuhlkena/VirtualRocks#88]
there's an option in the menu bar, but it hasn't been implemented yet. should be fairly easy, just needs to be done. 

could either be a toggle with a checkmark to show when it's in fullscreen or not, or the text can change from 'fullscreen' when out of full screen to 'exit fullscreen' when in fullscreen. we can track attributes, which would be more accurate than flags/changing whenever the button was pressed.

things to look at: 
https://stackoverflow.com/questions/7966119/display-fullscreen-mode-on-tkinter

**Comment by coden-s** [comment]
also f11 just straight up doesn't work

**Comment by yorngchhieng1** [comment]
I defined the key binding of F11 and ESC, one exists in main.
The other is in the pipeline gui. Pipeline GUI and main have repeated code.
