### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by coden-s** [kuhlkena/VirtualRocks#89]
part of the info/help menu probably, would be nice to have accessible offline.

some current things I'm looking at:
https://www.sphinx-doc.org/en/master/usage/quickstart.html
https://github.com/israel-dryer/ttkbootstrap/blob/version-0.5/docs/reference.rst

**Comment by coden-s** [comment]
seems like using rst would be nice but would be more helpful if we had better commented code, so this will likely take some effort once we're done.

**Comment by kuhlkena** [comment]
currently, we can only get to the docs from within the app.

if we have instructions for installing the project in the docs, we should have the docs accessible from outside of the app, preferably from the github page but could be elsewhere.

     ~Coden

**Comment by coden-s** [comment]
https://thomas-cokelaer.info/tutorials/sphinx/docstring_python.html
might be helpful to do stuff like this when we comment our code, works with the sphinx/rst docs I've set up already.
