### ISSUE TITLE
progressbar

### ISSUE THREAD

**Issue by kuhlkena** [kuhlkena/VirtualRocks#9]
create a visual aid which shows which step of the pipeline the program is on

1. Ready
2. Matching
3. Sparse
4. Dense
5. Cleaning
6. Meshing
7. Optimization
8. Texture
9. Done

**Comment by coden-s** [comment]
ways to think about it: 
base progress bar speed on number of pictures/meshes or their file sizes.
could also have two progress bars like Pix4D does, where one is the overall progress (or basically the progress in the current big step that you can't cancel out of), and a bar below it shows how what smaller steps are going on within that step (basically once the bar below fills up, the bar above increments and the bar below restarts).

**Comment by kuhlkena** [comment]
For now, I would only worry about keeping track of what step of the reconstruction we are on. It would be really nice if we could track it with more granularity than that but extracting more information than that from colmap is going to be next to impossible. One decision you will have to make is whether you want to make is if you want to have a progress bar for the whole thing (matching and meshing) or if you want to show it for matching and then restart it when the user starts meshing. I'll leave that up to you
