### ISSUE TITLE
save-recents

### ISSUE THREAD

**Issue by coden-s** [kuhlkena/VirtualRocks#96]
add recents to the menu bar, like a lil thing below what we currently have that lists the 3 most recently opened projects by names.

*** depends on super class

**Comment by coden-s** [comment]
we should have something,,, like a txt file within the code that matches up the name of the .pkl file with its path.

**Comment by kuhlkena** [comment]
depends on #97

**Comment by coden-s** [comment]
needs to track pkl file/path and probably the image directory each project is using

**Comment by coden-s** [comment]
recents are currently saving to a text file (as a dict with pickle path and image directory). it updates so that if you try to open a file you opened recently (like it was already on your recents list), then it removes where it was before and adds it to the end. 
can be used as a stack? where we can display the top 3 most recent by indexing from the end of the dict.

**Comment by coden-s** [comment]
would be nice to talk through how we want this to look. not sure of the best way to implement it in our menu...

**Comment by coden-s** [comment]
edge case: if we are opening a recent from the start menu, having one file in the recents is enough. might need to check to see what current pickle path is and if it's nothing, assume no project is open and the most recent one is a valid choice.

**Comment by coden-s** [comment]
depends on #22, but will pull because of how .pkl files are made and how it works with new_project()
